spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/coupon_example
#    username: root
#    password: 1234


  h2:
    console:
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:testdb'
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''